### ISSUE TITLE
Slow snap() with Thorlabs CMOS USB camera

### ISSUE THREAD

**Issue by jonfouchard** [AlexShkarin/pyLabLib#15]
Hi, 
I'm trying to use a Thorlabs Scientific Imaging CMOS USB camera (CS505MU) with pylablib. Camera works fine with Thorcam, but frame acquisition is very slow in pylablib (takes about 300ms) while camera can go up to 50fps in principle. Do you have any idea of where could be the issue ? 

Many thanks, 
Jon

**Comment by AlexShkarin** [comment]
Dear Jon,

Every time the ``snap`` method is called, it starts and then stops the acquisition, which frequently takes significant time. Hence, it does not work well for taking data at more than a couple of FPS. For that you can either use ``grab`` method (if you need to take a known number of frames, and you're OK with waiting until the acquisition is done), or set up an acquisition loop:
```python
# nframes=100 relates to the size of the frame buffer; the acquisition will continue indefinitely
cam.setup_acquisition(mode="sequence", nframes=100)  
cam.start_acquisition()
while True:  # acquisition loop
    cam.wait_for_frame()  # wait until a new frame is available
    frame = cam.read_oldest_image()  # get the oldest image which hasn't been read yet
    # ... process frame ...
    if time_to_stop:
        break
cam.stop_acquisition()
```
For even higher frame rates you can replace ``frame = cam.read_oldest_image()`` with ``frames = cam.read_multiple_images()``, which instead of a single oldest frame returns a list of all frames acquired since the last time this method was called.

You can find more info in the [documentation](https://pylablib.readthedocs.io/en/latest/devices/cameras_basics.html#acquisition-loop). You can also try and check out [pylablib-cam-control](https://pylablib-cam-control.readthedocs.io/en/latest/), which is a standalone software built on top of pylablib and designed to interface with all the cameras that it supports (including Thorlabs).

Sincerely,

Alexey.

**Comment by jonfouchard** [comment]
Dear Alexey,

thank you so much for your help, it works perfectly ! pylablib is super
useful. thanks for that.

Best wishes,
Jon

**Comment by AlexShkarin** [comment]
Thanks for the kind words! I'm glad it worked out!

Alexey.
