### ISSUE TITLE
Next Release Date?

### ISSUE THREAD

**Issue by LMSC-NTappy** [AlexShkarin/pyLabLib#16]
Dear Alex,

Hope you are doing great!

I just wanted to ask if you have a planned release date for the next update of the library. I am working on a camera plugin for pymodaq (https://github.com/CEMES-CNRS/PyMoDAQ) and if that's not too far away in the future I will postpone the release to avoid putting the dev branch in the setup.py (it's about that princeton instrument camera buffer fix).

Thank you very much in advance, 

take care

Nico

**Comment by AlexShkarin** [comment]
Dear Nico,

I'll most likely release the new version within the next week, together with a new version of [pylablib cam-control](https://github.com/SandoghdarLab/pyLabLib-cam-control). I hope you can wait till then. I agree, I would try to avoid using the dev branch directly, since the code there is often unstable and not very well tested.

Sincerely,

Alexey.

**Comment by LMSC-NTappy** [comment]
Dear Alexey,

I would have considered even 3 months as being a short release :)

Thank you so much for your work

Nico
