### ISSUE TITLE
IMAQ - start_acquisition() returns division by zero error

### ISSUE THREAD

**Issue by physici** [AlexShkarin/pyLabLib#5]
Hi, 
finally a working wrabber for IMAQ. So, many thanks first :)

Now, I'am trying to access a PCI1430 frame grabber with a line scanner attached to it (width=2048, height=1).

After initialization of the camera, I've tried to run the following code.
`cam.set_roi(0, 2048, 0, 1)`
`cam.start_acquisition()`

Here it returns the following ZeroDivisionError:
 File "c:\opt\python37\lib\site-packages\pylablib\aux_libs\devices\IMAQ.py", line 300, in _allocate_buffers
    frames_per_buff=max(self._buffer_allocation_size//self._frame_size,1)

Checking the error manually, I've seen that the function '_get_buffer_size()' returns zero, because of the following line:
`w,h=roi[1]-roi[0],roi[3]-roi[2]`

`cam.get_roi()`  returns (0, 0, 2048, 1)
So in the previous statement, w and h are calculated wrongly. 

A quick fix for me is replacing the line with 
`w,h=roi[2]-roi[0],roi[3]-roi[1]`

With that, I can read the image data correctly.

Do you have a chance to verify that?

Thanks,
Rainer

**Comment by AlexShkarin** [comment]
Thank you for bringing this to my attention! Indeed, the width and height calculations are currently done incorrectly.

The problem is more in the ordering of the result of `get_roi` method. Currently instead of returning it as `(vstart, vend, hstart, hend)` (as is written it its docstring), it returns `(vstart, hstart, vend, hend)`. 

This bug is fixed by replacing line `return l,t,l+w,t+h` with `return l,l+w,t,t+h` inside `get_roi` method. I've added the fix to the code, and it will be released in the next library version. The reason I never noticed that is because I only used `PhotonFocusIMAQCamera` camera class built on top of `IMAQCamera`. There `get_roi` method is overriden and it returns correctly ordered data.

Thank you again!

Alexey.

**Comment by physici** [comment]
OK, I will fix that in my fork as well. So it is consistent with yours. I will also create a pull request as I have added some functions to use the serial communication protocol via IMAQ.

You might also update your documentation that the IMAQ-library has been tested with the PCI1430 frame grabber from National Instruments.

Best regards,
Rainer
